name: Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme
      
      - name: Generate documentation
        run: |
          sphinx-quickstart --quiet --sep --dot=_ --project "My Project" --author "Your Name" --version "1.0" --release "1.0" --ext-autodoc
          sphinx-build -b html ./docs ./docs/_build/html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
